# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

VERILOG_SOURCES = $(shell pwd)/../rtl/complex.sv

MODULE = test_complex
TOPLEVEL = complex

include $(shell cocotb-config --makefiles)/Makefile.sim

