# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

VERILOG_SOURCES = $(shell pwd)/../rtl/complex.sv $(shell pwd)/../rtl/cvxif_complex.sv

MODULE = test_cvxif
TOPLEVEL = cvxif_complex

WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim